; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; WiFi & MQTT
lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit PWM Servo Driver Library@^2.4.0
    bblanchon/ArduinoJson@^6.21.3

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_INFO
    -DCONFIG_ARDUHAL_LOG_COLORS=1
    -DWIFI_SSID=\"your_wifi_ssid\"
    -DWIFI_PASSWORD=\"your_wifi_password\"
    -DMQTT_BROKER=\"your_mqtt_broker_ip\"
    -DMQTT_PORT=1883
