[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    madhephaestus/ESP32Servo@^1.1.2
board_build.flash_mode = dio
board_build.partitions = default.csv
